name: Commit Workflow

on:
  push:
    branches:
      - main

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check commit message
      id: check_commit
      run: |
        commit_message=$(git log --format=%B -n 1 ${{ github.sha }})
        if [[ $commit_message != *"EMB-"* ]]; then
          echo "::set-output name=commit_message::EMB-51"
        else
          echo "::set-output name=commit_message::$commit_message"
        fi

    - name: Create new commit
      run: |
        new_commit_message="${{ steps.check_commit.outputs.commit_message }}"
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit --amend -m "$new_commit_message"
        git push --force
