name: Commit Message Validation

on:
  push:
    branches:
      - main

jobs:
  validate-commit-message:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check Commit Message
        id: commit-message-check
        run: |
          commit_message=$(git log -1 --pretty=%B)
          if [[ ! $commit_message =~ EMB- ]]; then
            echo "::error::You need to link your commits to Jira issues"
            exit 1
          else
            echo "Commit message validation passed"
          fi
          
      - name: Display Commit Message
        run: |
          echo "Commit Message: ${{ github.event.commits[0].message }}"
